### ISSUE TITLE
setup GitHub pages

### ISSUE THREAD

**Issue by AHReccese** [openscilab/openscilab.com#1]
@sepandhaghighi 
please setup ci/cd and github pages.
Through [pm2](https://www.npmjs.com/package/pm2) we setup up a watcher on the build folder

`pm2 serve build/ 5000`

so the pm2 always will track the build/ folder, and whenever we commit, the ci/cd will rebuild the build folder.
here is a template ci/cd we use for the simple websites:

```yaml
name: website-frontend CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          yarn install  
          yarn build

env:
  CI: false
```
